log_filename="/www/gizmo_log.txt"
message_filename="/www/messages.txt"
rb_send_url="https://core.rock7.com/rockblock/MT"
rb_test_send_url="https://sometest/endpoint"
rb_imei="12345"
rb_username="mrsmith"
rb_password="password"
# notification settings
smtp_server="email-smtp.us-east-1.amazonaws.com"
smtp_server_port=587
smtp_account="ABCDEF1234"
smtp_password="abcdef123456"
smtp_destinations=["smith@smith.com","pork@gmail.com"]
sns_destinations=["18585551212"]
notify_subject="Message from Rockblock"
notify_from="noreply@mail.mymail.org"
reply_url="http://this/website"
aws_access_key_id = "ABCDEFG"
aws_secret_access_key = "ASDASD1234"
